apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-container
          image: "{{ .Values.image.repository}}:{{ .Values.image.tag}}"
          ports:
            - containerPort: {{ .Values.port }}
          env:
          - name: DB_HOST
            value: "10.134.0.3"
          - name: DB_NAME
            value: "ecommerce"
          - name: DB_USER
            value: "appuser"
          - name: DB_PASSWORD
            value: "Anjali@GKE2024!"
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi